# Generated by Django 4.1.1 on 2023-01-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='imgs/TagsPictures/', verbose_name='Image TAG'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(default='', max_length=25, verbose_name='Tag'),
        ),
    ]
