# Generated by Django 4.1.4 on 2023-01-24 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Announcement', '0002_annoucement_creator_annoucement_inscrits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
