# Generated by Django 4.1.1 on 2023-01-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0003_alter_annoucement_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO', 'Finalizado'), ('PAUSADO', 'Pausado')], default='ATIVO', max_length=20),
        ),
    ]
