# Generated by Django 4.1.1 on 2023-01-27 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0004_annoucement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='creation_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='annoucement',
            name='course',
            field=models.CharField(choices=[('ADS', 'Ads'), ('APICULTURA', 'Apicultura'), ('ALIMENTOS', 'Alimentos'), ('AGROINDUSTRIA', 'Agroindustria')], max_length=30),
        ),
    ]
