# Generated by Django 4.1.4 on 2023-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0006_alter_annoucement_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='course',
            field=models.CharField(choices=[('ADS', 'Ads'), ('APICULTURA', 'Apicultura'), ('ALIMENTOS', 'Alimentos'), ('AGROINDUSTRIA', 'Agroindustria')], default=False, max_length=30, null=True),
        ),
    ]
