# Generated by Django 4.1.1 on 2023-01-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='imgs/ProfilePictures/', verbose_name='Imagem do perfil'),
        ),
    ]
