# Generated by Django 4.1.4 on 2023-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_customuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexternal',
            name='institution',
            field=models.CharField(default='Não Informado', max_length=50, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='userexternal',
            name='schooling',
            field=models.CharField(default='Não Informado', max_length=200, null=True),
        ),
    ]
