# Generated by Django 4.1.1 on 2023-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_usercompany_city_alter_userexternal_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinternal',
            name='Qcreated',
            field=models.IntegerField(default=0),
        ),
    ]
