# Generated by Django 4.1.1 on 2023-01-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_userinternal_qcreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinternal',
            name='Qcreated',
        ),
        migrations.AddField(
            model_name='usercompany',
            name='Qcreated',
            field=models.IntegerField(default=0),
        ),
    ]
