# Generated by Django 4.1.1 on 2022-12-31 17:58

import Login.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', Login.models.UserManager()),
            ],
        ),
    ]
