# Generated by Django 4.1.1 on 2023-01-17 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_remove_userinternal_qcreated_usercompany_qcreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_external',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_internal',
        ),
        migrations.RemoveField(
            model_name='userinternal',
            name='schooling',
        ),
        migrations.CreateModel(
            name='CoordinationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=50, verbose_name='Instagram')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefone')),
                ('linkedin', models.CharField(max_length=50, verbose_name='Linkedin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
