# Generated by Django 4.1.1 on 2022-12-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_userexternal_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexternal',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
