# Generated by Django 4.1.1 on 2023-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_remove_customuser_is_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinationuser',
            name='Qcreated',
            field=models.IntegerField(default=0),
        ),
    ]
