# Generated by Django 4.1.4 on 2023-01-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_coordinationuser_qcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinternal',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
