# Generated by Django 4.1.1 on 2022-12-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_userexternal_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.city'),
        ),
        migrations.AlterField(
            model_name='userexternal',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.city'),
        ),
        migrations.AlterField(
            model_name='userexternal',
            name='schooling',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.schooling'),
        ),
        migrations.AlterField(
            model_name='userexternal',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.tags'),
        ),
    ]
