# Generated by Django 4.1.4 on 2023-01-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_alter_userinternal_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinternal',
            name='period',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
